[[redis.repositories.cdi-integration]]
= CDI Integration

Instances of the repository interfaces are usually created by a container, for which Spring is the most natural choice when working with Spring Data.
Spring offers sophisticated for creating bean instances.
Spring Data Valkey ships with a custom CDI extension that lets you use the repository abstraction in CDI environments.
The extension is part of the JAR, so, to activate it, drop the Spring Data Valkey JAR into your classpath.

You can then set up the infrastructure by implementing a CDI Producer for the javadoc:org.springframework.data.redis.connection.ValkeyConnectionFactory[] and javadoc:org.springframework.data.redis.core.ValkeyOperations[], as shown in the following example:

[source,java]
----
class ValkeyOperationsProducer {


  @Produces
  ValkeyConnectionFactory redisConnectionFactory() {

    LettuceConnectionFactory connectionFactory = new LettuceConnectionFactory(new ValkeyStandaloneConfiguration());
    connectionFactory.afterPropertiesSet();
	connectionFactory.start();

    return connectionFactory;
  }

  void disposeValkeyConnectionFactory(@Disposes ValkeyConnectionFactory redisConnectionFactory) throws Exception {

    if (redisConnectionFactory instanceof DisposableBean) {
      ((DisposableBean) redisConnectionFactory).destroy();
    }
  }

  @Produces
  @ApplicationScoped
  ValkeyOperations<byte[], byte[]> redisOperationsProducer(ValkeyConnectionFactory redisConnectionFactory) {

    ValkeyTemplate<byte[], byte[]> template = new ValkeyTemplate<byte[], byte[]>();
    template.setConnectionFactory(redisConnectionFactory);
    template.afterPropertiesSet();

    return template;
  }

}
----

The necessary setup can vary, depending on your JavaEE environment.

The Spring Data Valkey CDI extension picks up all available repositories as CDI beans and creates a proxy for a Spring Data repository whenever a bean of a repository type is requested by the container.
Thus, obtaining an instance of a Spring Data repository is a matter of declaring an `@Injected` property, as shown in the following example:

[source,java]
----
class RepositoryClient {

  @Inject
  PersonRepository repository;

  public void businessMethod() {
    List<Person> people = repository.findAll();
  }
}
----

A Valkey Repository requires javadoc:org.springframework.data.redis.core.ValkeyKeyValueAdapter[] and javadoc:org.springframework.data.redis.core.ValkeyKeyValueTemplate[] instances.
These beans are created and managed by the Spring Data CDI extension if no provided beans are found.
You can, however, supply your own beans to configure the specific properties of javadoc:org.springframework.data.redis.core.ValkeyKeyValueAdapter[] and javadoc:org.springframework.data.redis.core.ValkeyKeyValueTemplate[].

