[[spring-data-valkey-reference-documentation]]
= Spring Data Valkey
:revnumber: {version}
:revdate: {localdate}
:feature-scroll: true

_Spring Data Valkey provides Valkey connectivity and repository support for the Valkey database.
It eases development of applications with a consistent programming model that need to access Valkey data sources._

[horizontal]
xref:redis.adoc[Valkey] :: Valkey support and connectivity
xref:repositories.adoc[Repositories] :: Valkey Repositories
xref:observability.adoc[Observability] :: Observability Integration
https://github.com/spring-projects/spring-data-commons/wiki[Wiki] :: What's New, Upgrade Notes, Supported Versions, additional cross-version information.

Costin Leau, Jennifer Hickey, Christoph Strobl, Thomas Darimont, Mark Paluch, Jay Bryant

(C) 2008-{copyright-year} VMware, Inc.

Copies of this document may be made for your own use and for distribution to others, provided that you do not charge any fee for such copies and further provided that each copy contains this Copyright Notice, whether distributed in print or electronically.
